version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "sam-fredrickson"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "build(deps)"
      prefix-development: "build(deps-dev)"
    pull-request-branch-name:
      separator: "/"
